### Get all clients
GET http://localhost:3000/api/clients HTTP/1.1

### Get all projects
GET http://localhost:3000/api/projects HTTP/1.1

### Get all stack items
GET http://localhost:3000/api/technologies HTTP/1.1

### Get all stats
GET http://localhost:3000/api/stats HTTP/1.1

# ### Create a new message in a team channel
# POST http://localhost:3000/api/messages HTTP/1.1
# Content-Type: application/json

# {
#   "teamId": "li",
#   "channelId": "general",
#   "userId": 1,
#   "body": "Hi everyone!"
# }

# ### Delete a message
# DELETE http://localhost:3000/api/messages/5 HTTP/1.1
# Content-Type: application/json
